# Generated by Django 3.1.7 on 2021-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210513_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
